// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMLst7EHPzcsaxA1Hc7s4-KClpgULpO30',
    appId: '1:950073846783:web:f7332b4e631da0393615ca',
    messagingSenderId: '950073846783',
    projectId: 'healthbeing-322c7',
    authDomain: 'healthbeing-322c7.firebaseapp.com',
    storageBucket: 'healthbeing-322c7.appspot.com',
    measurementId: 'G-KPR46E0QQ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9tJ2glYTSu5Vlh2_jFFJaQt_4A5W3Rt8',
    appId: '1:950073846783:android:1f94578014fa820c3615ca',
    messagingSenderId: '950073846783',
    projectId: 'healthbeing-322c7',
    storageBucket: 'healthbeing-322c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ5z6NgW4tWCI14eMLB4U_rN8n9lW4uWw',
    appId: '1:950073846783:ios:ac5bb358a67b28d23615ca',
    messagingSenderId: '950073846783',
    projectId: 'healthbeing-322c7',
    storageBucket: 'healthbeing-322c7.appspot.com',
    iosBundleId: 'com.example.healthBeingTips',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ5z6NgW4tWCI14eMLB4U_rN8n9lW4uWw',
    appId: '1:950073846783:ios:ac5bb358a67b28d23615ca',
    messagingSenderId: '950073846783',
    projectId: 'healthbeing-322c7',
    storageBucket: 'healthbeing-322c7.appspot.com',
    iosBundleId: 'com.example.healthBeingTips',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMLst7EHPzcsaxA1Hc7s4-KClpgULpO30',
    appId: '1:950073846783:web:3045990ec456b9cd3615ca',
    messagingSenderId: '950073846783',
    projectId: 'healthbeing-322c7',
    authDomain: 'healthbeing-322c7.firebaseapp.com',
    storageBucket: 'healthbeing-322c7.appspot.com',
    measurementId: 'G-R62Z6YQ8KL',
  );
}
